package nl.hbgames.logic.game.singleplayer
{
   import nl.hbgames.utils.Random;
   
   public class AIPileData extends Object
   {
      
      private static const DEFAULT_PILE_SIZE:uint = 120;
      
      private static const MAX_PILE_SIZE:Object = {
         "nl":114,
         "en":102,
         "de":95,
         "fr":115,
         "es":116,
         "sv":102,
         "it":120,
         "no":100,
         "cs":100,
         "tr":100
      };
      
      private static const PILE_SHORTEN_RATIO:Number = 0.67;
      
      private static const DISTRIBUTION:Object = {
         "nl":{
            "A":8,
            "B":2,
            "C":2,
            "D":5,
            "E":22,
            "F":2,
            "G":3,
            "H":2,
            "I":6,
            "J":2,
            "K":3,
            "L":3,
            "M":3,
            "N":10,
            "O":8,
            "P":2,
            "Q":1,
            "R":5,
            "S":5,
            "T":5,
            "U":5,
            "V":2,
            "W":2,
            "X":1,
            "Y":1,
            "Z":2,
            "#":2
         },
         "en":{
            "A":9,
            "B":2,
            "C":2,
            "D":4,
            "E":12,
            "F":2,
            "G":3,
            "H":2,
            "I":9,
            "J":1,
            "K":1,
            "L":4,
            "M":2,
            "N":6,
            "O":9,
            "P":2,
            "Q":1,
            "R":6,
            "S":4,
            "T":6,
            "U":5,
            "V":2,
            "W":2,
            "X":1,
            "Y":2,
            "Z":1,
            "#":2
         },
         "de":{
            "A":6,
            "Ä":1,
            "B":2,
            "C":2,
            "D":3,
            "E":14,
            "F":2,
            "G":2,
            "H":3,
            "I":7,
            "J":1,
            "K":2,
            "L":2,
            "M":3,
            "N":7,
            "O":4,
            "Ö":1,
            "P":1,
            "Q":1,
            "R":5,
            "S":6,
            "T":5,
            "U":7,
            "Ü":1,
            "V":1,
            "W":1,
            "X":1,
            "Y":1,
            "Z":1,
            "#":2
         },
         "fr":{
            "A":12,
            "B":2,
            "C":2,
            "D":3,
            "E":18,
            "F":2,
            "G":2,
            "H":2,
            "I":11,
            "J":1,
            "K":1,
            "L":5,
            "M":3,
            "N":6,
            "O":8,
            "P":2,
            "Q":1,
            "R":6,
            "S":6,
            "T":6,
            "U":8,
            "V":2,
            "W":1,
            "X":1,
            "Y":1,
            "Z":1,
            "#":2
         },
         "es":{
            "A":12,
            "B":2,
            "C":2,
            "D":3,
            "E":18,
            "F":2,
            "G":2,
            "H":2,
            "I":11,
            "J":1,
            "K":1,
            "L":5,
            "M":3,
            "N":6,
            "O":8,
            "P":2,
            "Q":1,
            "R":6,
            "S":6,
            "T":6,
            "U":8,
            "V":2,
            "W":1,
            "X":1,
            "Y":1,
            "Z":1,
            "#":2
         },
         "sv":{
            "A":8,
            "B":2,
            "C":1,
            "D":5,
            "E":7,
            "F":2,
            "G":3,
            "H":2,
            "I":5,
            "J":2,
            "K":3,
            "L":5,
            "M":3,
            "N":6,
            "O":6,
            "P":2,
            "R":8,
            "S":8,
            "T":8,
            "U":3,
            "V":2,
            "X":1,
            "Y":1,
            "Z":1,
            "Å":2,
            "Ä":2,
            "Ö":2,
            "#":2
         },
         "it":{
            "A":14,
            "B":3,
            "C":6,
            "D":3,
            "E":11,
            "F":3,
            "G":2,
            "H":2,
            "I":12,
            "L":5,
            "M":5,
            "N":5,
            "O":15,
            "P":3,
            "Q":1,
            "R":6,
            "S":6,
            "T":6,
            "U":5,
            "V":3,
            "Z":2,
            "#":2
         },
         "no":{
            "A":7,
            "B":3,
            "C":1,
            "D":5,
            "E":9,
            "F":4,
            "G":4,
            "H":3,
            "I":5,
            "J":2,
            "K":4,
            "L":5,
            "M":3,
            "N":6,
            "O":4,
            "P":2,
            "R":6,
            "S":6,
            "T":6,
            "U":3,
            "V":3,
            "W":1,
            "Y":1,
            "Æ":1,
            "Ø":2,
            "Å":2,
            "#":2
         },
         "cs":{
            "O":6,
            "A":5,
            "E":5,
            "N":5,
            "I":4,
            "S":4,
            "T":4,
            "V":4,
            "D":3,
            "K":3,
            "L":3,
            "P":3,
            "R":3,
            "C":3,
            "H":3,
            "Í":3,
            "M":3,
            "U":3,
            "Á":2,
            "J":2,
            "Y":2,
            "Z":2,
            "B":2,
            "É":2,
            "Ě":2,
            "Ř":2,
            "Š":2,
            "Ý":2,
            "Č":1,
            "Ů":1,
            "Ž":1,
            "F":1,
            "G":1,
            "Ú":1,
            "Ň":1,
            "Ó":1,
            "Ť":1,
            "Ď":1,
            "X":1,
            "#":2
         },
         "tr":{
            "A":12,
            "E":8,
            "İ":7,
            "K":7,
            "L":7,
            "R":6,
            "N":5,
            "T":5,
            "I":4,
            "M":4,
            "O":3,
            "S":3,
            "U":3,
            "B":2,
            "D":2,
            "Y":2,
            "Ü":2,
            "C":2,
            "Ş":2,
            "Z":2,
            "Ç":2,
            "H":1,
            "P":1,
            "G":1,
            "F":1,
            "V":1,
            "Ö":1,
            "Ğ":1,
            "J":1,
            "#":2
         }
      };
       
      public function AIPileData()
      {
         super();
      }
      
      public static function GetMaxPileSize(param1:String) : uint
      {
         if(param1 in MAX_PILE_SIZE)
         {
            return Math.floor(MAX_PILE_SIZE[param1] * 0.67);
         }
         return Math.floor(120 * 0.67);
      }
      
      public static function GetInitialPile(param1:String) : Array
      {
         var _loc2_:* = 0;
         var _loc7_:* = 0;
         var _loc8_:Object = DISTRIBUTION[param1];
         var _loc3_:Array = [];
         var _loc10_:* = 0;
         var _loc9_:* = _loc8_;
         for(var _loc6_ in _loc8_)
         {
            _loc2_ = _loc8_[_loc6_];
            _loc7_ = 0;
            while(_loc7_ < _loc2_)
            {
               _loc3_.push(_loc6_);
               _loc7_++;
            }
         }
         Random.shuffle(_loc3_);
         var _loc4_:uint = GetMaxPileSize(param1);
         var _loc5_:Array = [];
         _loc4_ = _loc4_ > _loc3_.length?_loc3_.length:_loc4_;
         while(_loc4_ > 0)
         {
            _loc5_.push(_loc3_.shift());
            _loc4_--;
         }
         return _loc5_;
      }
   }
}
